sources:
  - GeistMono.glyphspackage
  - GeistMono-Italic.glyphspackage

familyName: "Geist Mono"
outputDir: ../fonts/GeistMono
cleanUp: true

buildVariable: false
buildStatic: true
buildTTF: true
buildOTF: true
buildWebfont: false

autohintTTF: false
autohintOTF: false
